png("plot3.png")
with(data, plot(Time, Sub_metering_1, type = "l",ylab = "Energy sub metering", xlab = ""))
with(data,lines(Time, Sub_metering_2, type="l", col ="red"))
with(data, lines(Time, Sub_metering_3, type="l", col="blue"))
legend("topright",lty = 1,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
