png("plot4.png")
par(mfrow=c(2,2))
with(data, plot(Time,Global_active_power,type ="l",ylab = "Global Active Power(kilowatts)",xlab=""))
with(data, plot(Time,Voltage,type ="l",ylab = "Voltage",xlab="datetime"))
with(data, plot(Time, Sub_metering_1, type = "l",ylab = "Energy sub metering", xlab = ""))
with(data,lines(Time, Sub_metering_2, type="l", col ="red"))
with(data, lines(Time, Sub_metering_3, type="l", col="blue"))
legend("topright",lty = 1,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(data, plot(Time,Global_reactive_power,type ="l",xlab="datetime"))
dev.off()